[package]
authors = ["Dirk Kretschmann <kretschmanndi@gmail.com>"]
edition = "2018"
license = "MIT"
name = "crawlbot"
version = "0.1.0"

[dependencies]
chrono = "0.4"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
websocket = "0.22.3"
